### PR TITLE
use docker run --link option to link a new cassandra node to another

### PR DESCRIPTION
**Pull request by clakech**
Hi,

I am using this image to setup a spark+cassandra cluster and I was wondering if we could use the docker run --link option to link new node to the first one instead of docker inspect command value pass to an environnement variable.

With this change, adding a node to the cluster is simpler, isn't it ?
```
docker run --name some-cassandra2 -d --link some-cassandra:cassandra cassandra:tag
```

WDYT? sorry if I am wrong, I am neither a docker expert, nor a C* one ;-)

### CODE REVIEW

**Comment by yosifkit** [comment]
Seems sane, but I would rather use 'cassandra' as the value if there is a link, so that when the linked container is restarted it can use the updated `/etc/hosts` entry to find the seed node again. Would it work with a DNS name rather than an IP address?

**Comment by clakech** [comment]
:+1: sounds good!

This PR already add value to the container in that state.

I need to test with cassandra hostname. Implementation may bit a bit different to check if link is used then use cassandra hostname but it is easy to do.

**Comment by clakech** [comment]
:checkered_flag: update branch and testing done. Seems ok with your proposal!

**Comment by yosifkit** [comment]
LGTM

**Comment by clakech** [comment]
Thanks, 

I send a PR to update the documentation here: https://github.com/docker-library/docs/pull/303

Could someone take a look ?

Bye

**Pull request merged**
