### PR TITLE
Don't restrict which settings can be set via environment

### LINKED ISSUE #12: Memory settings
Hello,
How are we supposed to configure the memory limits (Xmx) of cassandra using this image ?
No env variable for those ?

### PR DESCRIPTION
**Pull request by astopy**
Finds all environment variables named CASSANDRA_* rather than using a pre-defined list.

Automated build available at https://registry.hub.docker.com/u/astopy/cassandra/ for testing.

Closes #12

### CODE REVIEW

**Comment by yosifkit** [comment]
I am definitely on the "lets have only a small set that are commonly configured on start of a cassandra node" side. I don't see a reason to have all of them possible when it would be easier for a user to just supply a `cassandra.yaml`.  A couple line Dockerfile combined with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one that comes with these settings pre-configured.

I don't have the hard line of what should be configurable via ENV and what should require a custom yaml file, but I welcome input in defining where to draw.

**Comment by astopy** [comment]
I'd say it's more effort for the user to supply their own cassandra.yaml file than to set environment variables if the user is only changing one or two settings, though admittedly it's not _that_ much more effort so either way works for me.

It might be worth adding a note to the readme suggesting that users should overwrite cassandra.yaml, or I suspect you'll regularly receive questions asking how to change various settings.

**Comment by AnderUstarroz** [comment]
Adding our own yaml file will not overwrite some dynamically retrieved attributes like LISTEN_ADDRESS or BROADCAST_ADDRESS?

**Comment by yosifkit** [comment]
@AnderUstarroz, if you have your yaml with all the correct configuration, you should be able to just change the `docker run` to skip the entrypoint script. Either one of the following should work:

```console
$ docker run -d -v mount/config/file.yml:/etc/cassandra/cassandra.yaml --entrypoint=bash cassandra -c 'exec cassandra -f'
$ docker run  -d -v mount/config/file.yml:/etc/cassandra/cassandra.yaml --entrypoint=cassandra cassandra -f
```

**Comment by AnderUstarroz** [comment]
Ok I see, thanks for this  @yosifkit.

**Pull request closed without merging**
