### PR TITLE
Run as non-root by default (and allow arbitrary --user values)

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Worth also noting that 3.2 will not work without either this, or adding `-R` to the default flags (which is icky).

**Comment by yosifkit** [comment]
LGTM

**Comment by yosifkit** [comment]
Same `--user` improvement as https://github.com/docker-library/rabbitmq/pull/60; so OSX users can do the following and it should work.
```console
$ docker run -d -v /Users/...cassandra/:/var/lib/cassandra --user 1000:50 cassandra
```

**Comment by ale-batt** [comment]
@yosifkit I like the idea, and now my container isn't crashing when i try to create a volume.

**Comment by yosifkit** [comment]
It seems that Cassandra uses memory mapped files like mongodb,  and that is not possible in the virtual box shared folder. 😢

The only alternative is to setup nfs from host to vm.

**Pull request merged**
