### PR TITLE
update IP addresses in cassandra configuration in between restarts

### PR DESCRIPTION
**Pull request by mhariri**
This should resolve https://github.com/docker-library/cassandra/issues/67

### CODE REVIEW

**Comment by mhariri** [comment]
@tianon can we get this merged?

**Comment by jletroui** [comment]
+1 for this one

**Comment by yosifkit** [comment]
This PR would unfortunately prevent users from bind-mounting or using `COPY` for their own `cassandra.yaml`, since the proposed change would copy the original on top of it with each restart of the container.  Seeing that this is an important thing to fix, I have rebased #27 so that it is merge-able once again. If that fix is adequate, we can look to merge it.

**Comment by mhariri** [comment]
I'm totally OK with #27 , you can close this one if that one gets merged. :)

**Pull request closed without merging**
