### PR TITLE
Add cassandra-tools to the image, fixes #82

### LINKED ISSUE #82: sstabledump is missing
Not found in 3.7. Would be very useful for debugging/learning.

### PR DESCRIPTION
**Pull request by wederbrand**
To properly be able to debug and learn about Cassandra I've added cassandra-tools, including sstabledump, to the image.

fixes #82

### CODE REVIEW

**Comment by stickperson** [comment]
Any update on this?  Would be nice to have the tools there automatically.

**Comment by yosifkit** [comment]
@stickperson, thanks for the poke. Sometimes issues and PRs get lost in the flow. :disappointed:

I'll just do a quick rebase and re-apply it to all the versions!

**Comment by tianon** [comment]
The total size difference is ~790 kB. :sweat_smile:

**Comment by stickperson** [comment]
@yosifkit great, thanks. Can you push the image as well?

**Comment by yosifkit** [comment]
It should be up shortly after https://github.com/docker-library/official-images/pull/2732 merges.

**Pull request merged**
