### PR TITLE
client-to-node encryption (resolve #155 )

### LINKED ISSUE #155: Enable client-to-node encryption
Wanna to have an option to enable/disable client_encryption_options and to generate keystore to use.

### PR DESCRIPTION
**Pull request by fancywriter**

### CODE REVIEW

**Comment by tianon** [comment]
I'm definitely not comfortable embedding a certificate directly in the image (especially if we don't have to), so I think our best bet here is to point folks to the Cassandra documentation for how to enable TLS.

**Comment by fancywriter** [comment]
@tianon you're right, may be I can do it another way... this one was fastest... however could be much better and more flexible to provide it from the host... 🤔

**Comment by fancywriter** [comment]
@tianon could you give some piece of advice how to do it better? I have run out of the ideas...

Is it better to generate once provide keystore + truststore as a separate files inside git repository? And to copy them to image in Dockerfile? So that one can later download this truststore and connect to cassandra node with it.

Bad thing that if I need more than one node, I have to generate different keys there and put all of them on truststore on each node... how better to automate it with docker?

**Comment by tianon** [comment]
I'd recommend you generate a single keystore, store it in a Docker Secret object (https://docs.docker.com/engine/swarm/secrets/), and pass it to every service that needs it.  You could also use a Docker Config object for your YAML file (https://docs.docker.com/engine/swarm/configs/).

**Comment by tianon** [comment]
Given that this is pretty easy to accomplish (some standard configuration tweaks in Cassandra and generating and providing a keystore), and that we're not comfortable enabling this functionality like this by default (since it'll provide a pre-canned very insecure keystore for all users), I'm going to close; thanks! :+1:

**Pull request closed without merging**
