### PR TITLE
Add 3.0 release, drop 2.0 as it is now unsupported by upstream

### LINKED ISSUE #33: Add support for Cassandra 3.0

### PR DESCRIPTION
**Pull request by yosifkit**
See https://cassandra.apache.org/download/ for release and deprecation info.

Fixes #33

### CODE REVIEW

**Comment by yosifkit** [comment]
Added backports for jdk-8.

**Comment by tianon** [comment]
LGTM

**Comment by hseeberger** [comment]
That was quick ;-)
Thanks!

**Comment by hseeberger** [comment]
Ah, it seems like it's not yet available on Docker Hub.

**Pull request merged**
