### PR TITLE
new cassandra volume path

### PR DESCRIPTION
**Pull request by ltagliamonte**

### CODE REVIEW

**Comment by ltagliamonte** [comment]
Hello guys, do you have any updates on this PR?

**Comment by yosifkit** [comment]
Changes to the Dockerfiles look fine.  Could you drop the update.sh changes?  We have not determined how/if we support OSX on the helper scripts, but would want to update them across all `docker-library/` repos.  For now, you can run them in a container with a bind mount.  That is how @md5 does it :wink:.  `builpack-deps:curl` should work.

**Comment by ltagliamonte** [comment]
Done, I reverted the changes that i did on the update.sh script

**Comment by yosifkit** [comment]
Thanks! LGTM

**Comment by tianon** [comment]
:+1:

**Pull request merged**
