### PR TITLE
Add Cassandra 4.0 GPG key

### LINKED ISSUE #236: Hardcoded GPG keys in build are creating a dependency
The current dockerbuild template for Cassandra has hardcoded 4 members of the Cassandra PMC. Today's 4.0 release was built by a 5th person and as a result, broke on the key signing check. 

https://github.com/docker-library/cassandra/blob/08bea513f803c366493d823aa81a81d73e21c93f/Dockerfile.template#L65-L74

A PR has been issued to add the 5th person, but this feels like a ticking time bomb dependency. 

Ideally, the correct place to pull keys would be from the official ASF keys file for the project that authorizes the builds: https://dist.apache.org/repos/dist/release/cassandra/KEYS

### PR DESCRIPTION
**Pull request by emerkle826**
Closes #236

### CODE REVIEW

**Comment by emerkle826** [comment]
This can be closed if #237 is merged instead.

**Comment by yosifkit** [comment]
Added 4.0.0 bump and updated keys based on similar bit in the httpd image: https://github.com/docker-library/httpd/blob/5ed28f3fa96f71ef4c702a50c37aad86cf703551/2.4/Dockerfile#L84

**Comment by emerkle826** [comment]
Would #237 not be a better solution to avoid having to add more keys in the future?

**Comment by yosifkit** [comment]
> Would #237 not be a better solution to avoid having to add more keys in the future?

Yes and no. We embed the fingerprints explicitly in order to separate the processing of the fingerprint file and the using of the key for verification. Since the `KEYS` file can change at any point, downloading the `KEYS` file during build hides which keys could've been used for that build.

**Review by tianon — APPROVED** [review]

**Pull request merged**
