### PR TITLE
Run update.sh

### PR DESCRIPTION
**Pull request by yosifkit**
This may have to wait until cassandra fixes their apt repos.

```diff
diff --unified Packages-nongz Packages
--- Packages-nongz	2016-02-09 14:46:23.326707945 -0800
+++ Packages	2016-02-09 14:45:03.201804468 -0800
@@ -1,5 +1,5 @@
 Package: cassandra
-Version: 3.2
+Version: 3.2.1
 Architecture: all
 Maintainer: Eric Evans <eevans@apache.org>
 Installed-Size: 32278
@@ -11,30 +11,30 @@
 Homepage: http://cassandra.apache.org
 Priority: extra
 Section: misc
-Filename: pool/main/c/cassandra/cassandra_3.2_all.deb
-Size: 24306192
-SHA256: 09ea894ac7d1048cf93aa4fa14a619d1225a056c97d9193de59388b3c2624665
-SHA1: 2e5a50e5dd6b9de9426d588ea9142a0a5d495ea1
-MD5sum: 9330c576b0ac1613fb6ee4036b336e8c
+Filename: pool/main/c/cassandra/cassandra_3.2.1_all.deb
+Size: 24302452
+SHA256: 6b27061815d67a522c0083abbf9cf7e9f59c5a146cd46dc324a281ba990a7cda
+SHA1: f7db11c83508f8c8c0164cfcab8b1708b34acde1
+MD5sum: 9a5749a1f63021518fd6f7a7447e7d3e
 Description: distributed storage system for structured data
  Cassandra is a distributed (peer-to-peer) system for the management
  and storage of structured data.
 
 Package: cassandra-tools
 Source: cassandra
-Version: 3.2
+Version: 3.2.1
 Architecture: all
 Maintainer: Eric Evans <eevans@apache.org>
 Installed-Size: 22
-Depends: cassandra (= 3.2)
+Depends: cassandra (= 3.2.1)
 Homepage: http://cassandra.apache.org
 Priority: extra
 Section: misc
-Filename: pool/main/c/cassandra/cassandra-tools_3.2_all.deb
-Size: 4298
-SHA256: ed348b51644e2fa308bf49a65f4f1e72392516fa70bf9e0566013fdc2fccb58d
-SHA1: 29469092cbaa7c12b2a4b6058a46a77bbdcfbe05
-MD5sum: d9d71e517c812e9967cfa4b420b5610b
+Filename: pool/main/c/cassandra/cassandra-tools_3.2.1_all.deb
+Size: 4308
+SHA256: 85f76c0139258ed3a4a869c2f697d126665f4fbf7469478881daddc43aa05479
+SHA1: 737620b27f4480b710e0b3637435f4181c39f4b0
+MD5sum: 8f53ad4bf442d17f9177ba720e582641
 Description: distributed storage system for structured data
  Cassandra is a distributed (peer-to-peer) system for the management
  and storage of structured data.
```

### CODE REVIEW

**Comment by ltagliamonte** [comment]
@yosifkit can you relaunch the build?

**Comment by yosifkit** [comment]
Still failing :cry:

**Comment by tianon** [comment]
Yeah definitely an issue with upstream's repo that we can't really fix without them doing something about it: :disappointed:
```
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/32x/main/binary-amd64/Packages  Hash Sum mismatch
```
Caused by:
```diff
diff --git a/Packages-gzip b/Packages-nogzip
index ffb9191..78ea1f7 100644
--- a/Packages-gzip
+++ b/Packages-nogzip
@@ -1,5 +1,5 @@
 Package: cassandra
-Version: 3.2.1
+Version: 3.2
 Architecture: all
 Maintainer: Eric Evans <eevans@apache.org>
 Installed-Size: 32278
@@ -11,30 +11,30 @@ Replaces: apache-cassandra1
 Homepage: http://cassandra.apache.org
 Priority: extra
 Section: misc
-Filename: pool/main/c/cassandra/cassandra_3.2.1_all.deb
-Size: 24302452
-SHA256: 6b27061815d67a522c0083abbf9cf7e9f59c5a146cd46dc324a281ba990a7cda
-SHA1: f7db11c83508f8c8c0164cfcab8b1708b34acde1
-MD5sum: 9a5749a1f63021518fd6f7a7447e7d3e
+Filename: pool/main/c/cassandra/cassandra_3.2_all.deb
+Size: 24306192
+SHA256: 09ea894ac7d1048cf93aa4fa14a619d1225a056c97d9193de59388b3c2624665
+SHA1: 2e5a50e5dd6b9de9426d588ea9142a0a5d495ea1
+MD5sum: 9330c576b0ac1613fb6ee4036b336e8c
 Description: distributed storage system for structured data
  Cassandra is a distributed (peer-to-peer) system for the management
  and storage of structured data.
 
 Package: cassandra-tools
 Source: cassandra
-Version: 3.2.1
+Version: 3.2
 Architecture: all
 Maintainer: Eric Evans <eevans@apache.org>
 Installed-Size: 22
-Depends: cassandra (= 3.2.1)
+Depends: cassandra (= 3.2)
 Homepage: http://cassandra.apache.org
 Priority: extra
 Section: misc
-Filename: pool/main/c/cassandra/cassandra-tools_3.2.1_all.deb
-Size: 4308
-SHA256: 85f76c0139258ed3a4a869c2f697d126665f4fbf7469478881daddc43aa05479
-SHA1: 737620b27f4480b710e0b3637435f4181c39f4b0
-MD5sum: 8f53ad4bf442d17f9177ba720e582641
+Filename: pool/main/c/cassandra/cassandra-tools_3.2_all.deb
+Size: 4298
+SHA256: ed348b51644e2fa308bf49a65f4f1e72392516fa70bf9e0566013fdc2fccb58d
+SHA1: 29469092cbaa7c12b2a4b6058a46a77bbdcfbe05
+MD5sum: d9d71e517c812e9967cfa4b420b5610b
 Description: distributed storage system for structured data
  Cassandra is a distributed (peer-to-peer) system for the management
  and storage of structured data.
```

Anyone know where the proper place to report this would be?  It's not really an issue with Cassandra itself perse, and each project has slightly different preferences on where hosting, etc issues ought to be reported. :confused:

**Comment by tianon** [comment]
This one's especially strange because both https://cassandra.apache.org/ and https://cassandra.apache.org/download/ have no mention of 3.2 at all (minus the blurb about `Even-numbered releases (e.g. 3.2) contain new features`). :confused:

**Comment by tianon** [comment]
I've just updated/rebased this to only include 3.2, since that's the only one still failing.

See also https://github.com/docker-library/cassandra/commit/d0a316423d957077b59f5d37ace76b5f4cc84a4c (update everything else) and https://github.com/docker-library/cassandra/commit/13a08c6fb1f02a68060d632ac75b2caed92500e7 (add 3.3).

**Comment by ltagliamonte** [comment]
Why we do not use the datastax repo?
```
deb http://debian.datastax.com/community stable main
```

**Comment by tianon** [comment]
@ltagliamonte yeah, I was thinking that myself after re-reading https://wiki.apache.org/cassandra/DebianPackaging (which says essentially "here go use DataStax -- if you _must_, we host one too")

I wonder whether it's still worth reporting the issue with upstream's official repo though?

**Comment by ltagliamonte** [comment]
@tianon if you want go ahead with reporting the issue. 
For my experience the most updated repo is the datastax one.

**Comment by tianon** [comment]
Filed as https://issues.apache.org/jira/browse/CASSANDRA-11180, but it's worth noting that we've pushed 3.3 to the Hub in the mean-time, and that it's probably worth updating to that if you haven't already (especially since 3.2 isn't even listed on the main Cassandra homepage or downloads page anymore).

Hopefully they'll either fix it or let us know we should abandon and use DataStax instead (or both!)

**Comment by tjake** [comment]
Should be working now

**Comment by tjake** [comment]
Also 33x is out :)

**Comment by tianon** [comment]
:metal: thanks @tjake!  While we have you for a moment, any thoughts on whether we should continue with these or switch to the DataStax repos? :innocent:

(We've already added 33x in master, and I've restarted the Travis job here so we can verify before we merge. :+1:)

**Comment by tianon** [comment]
Wooooot, green! :tada:

**Pull request merged**
